# Generated by Django 5.0.6 on 2024-05-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('profile', models.ImageField(upload_to='uploads')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
